# Generated by Django 2.0.4 on 2018-04-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20180421_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.TextField(default='Title Unknown'),
            preserve_default=False,
        ),
    ]
